var inews = {
    news: [
        {
            id: 1,
            fTitle: '疫情防控不停歇 垃圾分类要同行',
            fReleaseTime: '2020-04-15',
            fContent: '<p style="color: #000;font-family:宋体;font-size:16px;background-color: #fff;">  2020年是全区生活垃圾分类工作决战决胜的关键年，河上镇将围绕提质扩面，持续深入推进农村生活垃圾分类质量，在现有基础上不断提升群众的参与率和分类的正确率。</p><p style="color: #000;font-family:宋体;font-size:16px;/* background-color:#91BEB9; */text-align:center;"><img src="http://uptown.xsnet.cn/uploadfile/2020/0330/20200330102227494.jpg" data-ke-src="http://uptown.xsnet.cn/uploadfile/2020/0330/20200330102227494.jpg" title="1.jpg" border="0" width="500" height="376" style="width:500px;height:376px;"></p><p style="color: #000;font-family:宋体;font-size:16px;/* background-color:#91BEB9; */">  继续深入推进垃圾分类全覆盖，实现集镇沿街商铺、农贸市场垃圾分类定时定点投放；依托美丽厂区建设，推进企业垃圾分类和科学处置。继续深入推进各类垃圾处置全覆盖，努力破解装修垃圾、苗木垃圾等处理难问题。</p><p style="color: #000;font-family:宋体;font-size:16px;/* background-color:#91BEB9; */">  疫情发生以来，百姓响应号召宅在家中，垃圾增量明显，但你知道日常防护所使用的口罩、手套、防护服怎么处理吗？属于其他垃圾？还是有害垃圾？来看看，河上的垃圾分类做得很到位。</p><p style="color: #000;font-family:宋体;font-size:16px;/* background-color:#91BEB9; */">  垃圾分类只有起点，没有终点，即使在新冠肺炎的阻挠下，河上镇的卫生工作人员始终没有停下脚步，带上口罩，穿上工作服不顾风雨，始终坚守在自己的岗位上，为抗击疫情默默的贡献着自己的一份力量。</p><p style="color: #000;font-family:宋体;font-size:16px;/* background-color:#91BEB9; */">  <strong>消毒不停</strong></p><p style="color: #000;font-family:宋体;font-size:16px;/* background-color:#91BEB9; */">  每天安排人员对村内各个点位进行消杀。</p><p style="color: #000;font-family:宋体;font-size:16px;/* background-color:#91BEB9; */">  <strong>宣传不停</strong></p><p style="color: #000;font-family:宋体;font-size:16px;/* background-color:#91BEB9; */">  各村（社区）动员各界力量全面开展入户宣传，普及垃圾分类的重要性和具体要求。</p><p style="color: #000;font-family:宋体;font-size:16px;/* background-color:#91BEB9; */">  <strong>垃圾收运不停歇</strong></p><p style="color: #000;font-family:宋体;font-size:16px;/* background-color:#91BEB9; */">  面对垃圾处理的巨大压力，河上镇的环卫工人始终奔波在大街小巷，全力确保疫情期间的垃圾收运工作。</p><p style="color: #000;font-family:宋体;font-size:16px;/* background-color:#91BEB9; */">  <strong>设废弃口罩回收桶</strong></p><p style="color: #000;font-family:宋体;font-size:16px;/* background-color:#91BEB9; */">  疫情期间，临时增加废弃口罩一类。</p><p style="color: #000;font-family:宋体;font-size:16px;/* background-color:#91BEB9; */">  最后我们来了解下疫情防护期间我们个人防护品垃圾到底该如何分类</p><p style="color: #000;font-family:宋体;font-size:16px;/* background-color:#91BEB9; */">  疫情期间的特殊有害垃圾主要是两大类：</p><p style="color: #000;font-family:宋体;font-size:16px;/* background-color:#91BEB9; */">  一是居民丢弃的口罩、各类固、液体消毒液；</p><p style="color: #000;font-family:宋体;font-size:16px;/* background-color:#91BEB9; */">  二是经核实有发热症状的居民家庭产生的所有生活垃圾。</p><p style="color: #000;font-family:宋体;font-size:16px;/* background-color:#91BEB9; */">  请将废弃口罩等特殊有害垃圾定点投放至专门的收集桶。暂不具备条件的地方，可投放至红色的有害垃圾桶或用其他符合安全密闭要求的垃圾桶进行替代。</p><p style="color: #000;font-family:宋体;font-size:16px;/* background-color:#91BEB9; */">  新冠肺炎疫情，是一次危机，更是一次挑战。既给我们上了一节病毒防控实践课，也给我们上了一堂健康与环境实验课。垃圾分类与防控疫情息息相关，做好垃圾分类，就是为这场阻击战贡献力量，为我们美好的明天增添希望！</p>​'
        },
        {
            id: 2,
            fTitle: '中国垃圾分类进入“强制时代”',
            fReleaseTime: '2020-03-31',
            fContent: '<p><strong><span style="font-size: 16px;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;央视网消息：</span></strong><span style="color: rgb(51, 51, 51); font-family: Arial, 宋体; font-size: 16px; background-color: rgb(255, 255, 255);">今年以来，北京、上海、广东等超大城市先后就生活垃圾管理进行了修法或立法，通过约束机制，逐步的改变居民随意投放垃圾的习惯，业内人士指出垃圾分类立法重点是树立敬畏意识，有利于提高公众的环境意识和法律意识，鼓励公众参与环境保护，并对污染环境者形成监督压力。</span><span style="font-size: 16px;">&#8203;</span><br></p><p><span style="font-size: 16px;"><p style="text-align: center; font-size: 16px; font-family: Arial, 宋体; color: rgb(51, 51, 51); background-color: rgb(255, 255, 255);">&nbsp; &nbsp; &nbsp; &nbsp;&nbsp;<img src="https://p2.img.cctvpic.com/photoworkspace/contentimg/2019/06/24/2019062414364115196.jpg" alt="新闻观察：中国垃圾分类进入“强制时代”" isflag="1" data-spm-anchor-id="0.0.0.i9" style="font-family: &quot;sans serif&quot;, tahoma, verdana, helvetica; font-size: 12px;"></p><p style="font-size:16px;font-family:Arial, 宋体;color:#333333;background-color:#FFFFFF;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;再过一周，《上海市生活垃圾管理条例》将正式开始实施，在社区里不仅垃圾分类成了热词，而且大部分居民都已行动起来，在倒垃圾时已经将垃圾分类用不同的塑料袋装着倒入不同的垃圾桶。</p></span><span style="font-size: 16px;"><p style="font-size:16px;font-family:Arial, 宋体;color:#333333;background-color:#FFFFFF;">&emsp;&emsp;<strong>上海市民 刘燕萍：</strong>我们平时吃的牛奶，它外面的壳，现在已经有新的规定了，以前我们认为是扔在干垃圾里面，其实这应该把它分开。</p><p style="font-size:16px;font-family:Arial, 宋体;color:#333333;background-color:#FFFFFF;">&emsp;&emsp;上海率先将垃圾分类纳入法制框架，通过立法明确了可回收物、有害垃圾、湿垃圾和干垃圾4种生活垃圾分类标准，旅店、餐馆不得主动提供一次性用品。首次明确对生活垃圾全流程进行分类，确立分类投放管理责任人制度和相应法律责任等。比如，个人如果混合投放垃圾最高可罚款200元，单位混装混运最高可罚款5万元。</p><p style="font-size:16px;font-family:Arial, 宋体;color:#333333;background-color:#FFFFFF;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;数据显示，中国人均日产垃圾1.2公斤，并且每年以10%的增长率递增，垃圾处理已经到了刻不容缓的地步。从今年开始，全国地级及以上城市全面开启了生活垃圾分类工作，在先行先试的46个重点城市多地已初步建成生活垃圾分类、收集、运输、处理体系，不少城市也纷纷加入到推行生活垃圾强制分类的队伍中来。</p><p style="font-size:16px;font-family:Arial, 宋体;color:#333333;background-color:#FFFFFF;">&emsp;&emsp;5月底，北京市提出将推动学校、医院等公共机构以及商业办公楼宇、旅游景区、酒店等经营性场所开展垃圾强制分类，并逐步实现全覆盖。如果不分类就不收运，多次违规拒不整改的还将收到处罚，并纳入信用管理体系。通过约束机制，逐步改变居民随意投放垃圾的习惯。</p><p style="font-size:16px;font-family:Arial, 宋体;color:#333333;background-color:#FFFFFF;">&emsp;&emsp;在广州，《广州市生活垃圾分类管理条例》于去年7月1日起开始实施，常态化执法检查成为重要抓手。</p><p style="font-size:16px;font-family:Arial, 宋体;color:#333333;background-color:#FFFFFF;">&emsp;&emsp;业内人士指出，垃圾分类立法重点是树立敬畏意识，除了引导市民的分类意识，建立配套设施也十分重要。赋予公民环境权，有利于提高公众的环境意识和法律意识，鼓励公众参与环境保护，并对污染环境者形成监督压力。</p>&#8203;<br></span></p>'
        },
        {
            id: 3,
            fTitle: '生活垃圾分类指导手册',
            fReleaseTime: '2020-03-30',
            fContent: '<p style="text-align:center;font-weight:normal;font-size:27px;font-family:微软雅黑, &quot;color:#333333;background-color:#FFFFFF;"></p><p style="text-align:justify;color:#404040;font-family:&quot;font-size:18px;"><span style="font-size:16px;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;近年来,我国加速推行垃圾分类制度,全国垃圾分类工作由点到面、逐步启动、成效初显。近日,习近平总书记对垃圾分类工作作出重要指示:推行垃圾分类,关键是要加强科学管理、形成长效机制、推动习惯养成。他还强调,垃圾分类工作就是新时尚,垃圾综合处理需要全民参与……</span></p><p style="text-align:center;color:#404040;font-family:&quot;font-size:18px;"><span style="font-size:16px;"><img src="http://www.xinhuanet.com/2019-06/12/1124609793_15602948739341n.jpg" data-ke-src="http://www.xinhuanet.com/2019-06/12/1124609793_15602948739341n.jpg"><br></span></p><p style="text-align:justify;color:#404040;font-family:&quot;font-size:18px;"><span style="font-size:16px;">&emsp;&emsp;推进垃圾分类,需要在“方便”与“不便”之间寻找平衡,离不开环卫部门、社区、物业公司以及居民的共同努力。现实中,收运处理渠道建设如何?居民如何真正养成垃圾分类的生活习惯?从规范立法到行为普及还有多远的距离?针对这些问题,本报记者采访了垃圾分类链条上的几个环节,推出本版专题报道,敬请关注。</span></p><p style="text-align:justify;color:#404040;font-family:&quot;font-size:18px;"><span style="font-size:16px;">&emsp;&emsp;●&emsp;实行垃圾分类,关系广大人民群众生活环境,关系节约使用资源,也是社会文明水平的一个重要体现</span></p><p style="text-align:justify;color:#404040;font-family:&quot;font-size:18px;"><span style="font-size:16px;">&emsp;&emsp;●&emsp;目前,我国垃圾分类尚未完成行为普及,主要原因是宣传教育不足,垃圾分类还没有成为公众的自觉行动,公众存在“所有垃圾是一辆车拉走的”“分了也白分”的刻板印象</span></p><p style="text-align:justify;color:#404040;font-family:&quot;font-size:18px;"><span style="font-size:16px;">&emsp;&emsp;●&emsp;垃圾分类立法重点是树立敬畏意识。除了引导市民的分类意识,建立配套设施也十分重要。赋予公民环境权,有利于提高公众的环境意识和法律意识,鼓励公众参与环境保护,并对污染环境者形成监督压力</span></p><p style="text-align:justify;color:#404040;font-family:&quot;font-size:18px;"><span style="font-size:16px;">&emsp;&emsp;垃圾分类看似是“小事”,实则是“大事”。</span></p><p style="text-align:justify;color:#404040;font-family:&quot;font-size:18px;"><span style="font-size:16px;">&emsp;&emsp;“推行垃圾分类,关键是要加强科学管理、形成长效机制、推动习惯养成。”近日,中共中央总书记、国家主席、中央军委主席习近平对垃圾分类工作作出重要指示。</span></p><p style="text-align:justify;color:#404040;font-family:&quot;font-size:18px;"><span style="font-size:16px;">&emsp;&emsp;习近平指出,要开展广泛的教育引导工作,让广大人民群众认识到实行垃圾分类的重要性和必要性,通过有效的督促引导,让更多人行动起来,培养垃圾分类的好习惯,全社会人人动手,一起来为改善生活环境作努力,一起来为绿色发展、可持续发展作贡献。</span></p><p style="text-align:justify;color:#404040;font-family:&quot;font-size:18px;"><span style="font-size:16px;">&#8203;<br></span></p><span style="font-size:16px;"><div style="text-align:justify;"></div></span><p></p>'
        }
    ]
}
module.exports = inews